services:
  ai_photo_cleaner:
    build: .
    container_name: ai_photo_cleaner_app
    ports:
      - "8081:8081"    # Metro bundler
      - "19000:19000"  # Expo Dev Tools
      - "19001:19001"  # Expo Dev Server (LAN)
      - "19002:19002"  # Expo Dev Server (localhost)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEBUG=true
    stdin_open: true
    tty: true
    networks:
      - expo_network

networks:
  expo_network:
    driver: bridge